version: '3'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    container_name: "redis"
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
     - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app:rw
    command: python3 hello.py
